ARDUINO_DIR=/usr/share/arduino
AVR_TOOLS_PATH=/usr/bin
BOARD_TAG=uno
#BOARD_TAG=atmega328
ARDUINO_PORT=/dev/ttyACM0
#/dev/ttyUSB0
AVRDUDE_CONF=$(ARDUINO_DIR)/hardware/tools/avrdude.conf
ARDUINO_LIBS= 


TARGET=serial

include  ../arduino-mk/Arduino.mk
