ARDUINO_DIR=/usr/share/arduino
AVR_TOOLS_PATH=/usr/bin
BOARD_TAG=atmega328
ARDUINO_PORT=/dev/ttyUSB1
AVRDUDE_CONF=$(ARDUINO_DIR)/hardware/tools/avrdude.conf
ARDUINO_LIBS=IRremote


TARGET=hello2

include  ../arduino-mk/Arduino.mk
