ARDUINO_DIR=/usr/share/arduino
AVR_TOOLS_PATH=/usr/bin
# BOARD_TAG=attiny44-20
BOARD_TAG=attiny84-20
ALTERNATE_CORE=attiny
ARDUINO_PORT=/dev/ttyACM0
ISP_PORT=/dev/ttyACM*
AVRDUDE_CONF=$(ARDUINO_DIR)/hardware/tools/avrdude.conf
#ARDUINO_LIBS=Servo

TARGET=blink

include  ../arduino-mk/Arduino.mk
# USE make ispload instead of make upload !!!
