ARDUINO_DIR=/usr/share/arduino
AVR_TOOLS_PATH=/usr/bin
#BOARD_TAG=mega
BOARD_TAG=atmega328
ARDUINO_PORT=/dev/ttyUSB0
AVRDUDE_CONF=$(ARDUINO_DIR)/hardware/tools/avrdude.conf
ARDUINO_LIBS=VirtualWire ServoTimer2 SerialDebug
#ARDUINO_LIBS= ServoTimer2 twi Nunchuck Wire VirtualWire
USER_LIB_PATH=../user_libs


TARGET=paperbot

include  ../arduino-mk/Arduino.mk
