ARDUINO_DIR=/usr/share/arduino
AVR_TOOLS_PATH=/usr/bin
BOARD_TAG=mega
#BOARD_TAG=atmega328
ARDUINO_PORT=/dev/ttyUSB0
AVRDUDE_CONF=$(ARDUINO_DIR)/hardware/tools/avrdude.conf
ARDUINO_LIBS=BaseNew VirtualWire Nunchuck Wire twi

TARGET=rfnunchuck

include  /usr/share/arduino/custom/Arduino.mk
