ARDUINO_DIR=/usr/share/arduino
AVR_TOOLS_PATH=/usr/bin
#BOARD_TAG=mega
BOARD_TAG=atmega328
ARDUINO_PORT=/dev/ttyUSB1
AVRDUDE_CONF=$(ARDUINO_DIR)/hardware/tools/avrdude.conf
ARDUINO_LIBS= VirtualWire
USER_LIB_PATH=../user_libs/


TARGET=rfcomm

include  ../arduino-mk/Arduino.mk
