ARDUINO_DIR=/usr/share/arduino
AVR_TOOLS_PATH=/usr/bin
#BOARD_TAG=mega
BOARD_TAG=atmega328
ARDUINO_PORT=/dev/ttyUSB0
AVRDUDE_CONF=$(ARDUINO_DIR)/hardware/tools/avrdude.conf
ARDUINO_LIBS=Servo
#ARDUINO_LIBS= ServoTimer2 twi Nunchuck Wire VirtualWire


TARGET=popsiclebot

include  ../arduino-mk/Arduino.mk
