ARDUINO_DIR=/usr/share/arduino
AVR_TOOLS_PATH=/usr/bin
BOARD_TAG=uno
ARDUINO_PORT=/dev/ttyACM0
AVRDUDE_CONF=$(ARDUINO_DIR)/hardware/tools/avrdude.conf
ARDUINO_LIBS=Servo


TARGET=partySpy

include  ../arduino-mk/Arduino.mk
