ARDUINO_DIR=/usr/share/arduino
AVR_TOOLS_PATH=/usr/bin
#BOARD_TAG=mega
BOARD_TAG=atmega328
#BOARD_TAG=nano328
#BOARD_TAG=uno
#ARDUINO_PORT=/dev/ttyACM0
ARDUINO_PORT=/dev/ttyUSB0
AVRDUDE_CONF=$(ARDUINO_DIR)/hardware/tools/avrdude.conf
ARDUINO_LIBS=Servo


TARGET=servo90

include  ../arduino-mk/Arduino.mk
