ARDUINO_DIR=/usr/share/arduino
AVR_TOOLS_PATH=/usr/bin
BOARD_TAG=mega
ARDUINO_PORT=/dev/ttyUSB0
AVRDUDE_CONF=$(ARDUINO_DIR)/hardware/tools/avrdude.conf
ARDUINO_LIBS= Servo


TARGET=pot

include  ../arduino-mk/Arduino.mk
